// creating objects
const ROOT_NAV = document.getElementById('nav')
const ROOT_HEADER = document.getElementById('header')
const ROOT_ABOUT = document.getElementById('about')
const  ROOT_BENEFITS = document.getElementById('benefits')
const ROOT_WORKS = document.getElementById('works')
const ROOT_PORTFOLIO = document.getElementById('portfolio')
const ROOT_SKILLS = document.getElementById('skills')
const ROOT_TEAM = document.getElementById('team')
const ROOT_TESTIMONIALS = document.getElementById('testimonials')
const ROOT_NEWS = document.getElementById('news')
const ROOT_REGISTRATION = document.getElementById('registration')
const ROOT_FOOTER = document.getElementById('footer')
const ROOT_BURGER = document.getElementById('burger')